'use strict';

const { DEFAULT_SPLUNK_URL } = require('../lib/splunk-url');

module.exports = {
    fileCounter: 1,
    SPLUNK_URL: DEFAULT_SPLUNK_URL,
    files: [],
    folders: [],
    ideFolders: {},
    collapsedExplorerFolders: new Set(),
    activeFileId: null,
    fileMru: [],
    currentProjectPath: null,
    currentProjectName: 'No project loaded',
    shiftTapCount: 0,
    shiftTimer: null,
    quickSearchSelectedIndex: 0,
    quickSearchMode: 'file',
    modalMode: 'create',
    modalTargetFileId: null,
    currentGit: null,
    gitSyncSettings: {
        splunkUrl: '',
        remoteUrl: '',
        remoteName: 'origin',
        sharedBranch: 'main',
        gitUserName: '',
        gitUserEmail: '',
    },
    queryVersions: [],
    queryHasUnsavedChanges: false,
    selectedVersionHashes: [],
    queryRefreshGeneration: 0,
    currentQueryText: '',
    previewMode: 'preview',
    historySidebarMode: 'history',
    versionTags: [],
    tagPopupTargetHash: null,
    tagPopupClearMode: false,
    confirmResolve: null,
    restoreParentByFileId: new Map(),
    forcedDraftByFileId: new Set(),
    userDraftByFileId: new Set(),
    liveAceQueryByFileId: new Map(),
    liveDraftDebounceByFileId: new Map(),
    _findOverlay: null,
    _lastFindQuery: '',
    _findWasActive: false,
};
